############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Re Protocol"
url = "/re"
weight = 3

[[main]]
name = "Works"
url = "/works"
weight = 4

[[main]]
weight = 5
name = "Services"
hasChildren = true

[[main]]
parent = "Services"
name = "Relayers"
url = "relayers/"

[[main]]
parent = "Services"
name = "Public Endpoints"
url = "public_endpoints/"

[[main]]
parent = "Services"
name = "State Sync"
url = "state_sync/"

[[main]]
parent = "Services"
name = "Docker Image Hosting"
url = "docker_images/"

# footer menu
[[footer]]
name = "Contact Us"
url = "/contact"
weight = 1

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
